[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "npm run dev"
  port = 9002
  targetPort = 4000

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/__/*"
  to = "/__/*"
  status = 200
